accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('sign-up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),     
]

lecture/urls.py
from django.urls import path
from . import views

app_name = 'lecture'

urlpatterns = [
     path('', views.index,  name="index"),
     path('<int:lecture_id>/', views.detail, name="detail"),
     path('new/', views.new, name="new"),
     path('create/', views.create, name="create"),
     path('<int:lecture_id>/edit/', views.edit, name="edit"),
     path('<int:lecture_id>/update/', views.update, name="update"),
     path('<int:lecture_id>/delete/', views.delete, name="delete"),
     path('<int:lecture_id>/like/', views.like, name="like"),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name="main"),
]

mutflearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('lecture/', include('lecture.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # production환경에서는 구동하지 않는다

accounts/models.py
from django.db import models

# Create your models here.

lecture/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Lecture(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    body = models.TextField() # 대용량의 타입의 필드
    image = models.ImageField(upload_to='lecture', null=True)
    created_at = models.DateTimeField() # 날짜 타입의 필드
    liked_lectures = models.ManyToManyField(User, related_name='liked_lectures')
    title = models.CharField(max_length=200, null=True)
    video_key = models.CharField(max_length=12, null=True)

    def __str__(self):
        if self.user:
            return f'{self.user.get_username()}: {self.body}'
        else:
            return f'{self.body}'

main/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.

def sign_up(request):
    context = {}

    if request.method == 'POST':
        if (request.POST.get('username') and 
            request.POST.get('password') and 
            request.POST.get('password') == request.POST.get('password_check')):

            # Django 내장 create_user 함수를 이용한다.
            new_user = User.objects.create_user(
                username = request.POST.get('username'),
                password = request.POST.get('password'),
            )

            # 로그인처리
            auth.login(request, new_user)
            return redirect('main:main')

        else:
            context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'
    
    return render(request, 'accounts/sign_up.html', context)

def login(request):
    context = {}

    if request.method == 'POST':
        if request.POST.get('username') and request.POST.get('password'):
            
            # authenticate함수를 사용한다., 첫번째 인자는 request
            # db에는 암호화된 password가 저장되기 때문에 직접비교는 불가능 하기때문에 authenticate함수를 이용
            user = auth.authenticate(
                request,
                username = request.POST.get('username'),
                password = request.POST.get('password'),
            )

            if user is not None:

                auth.login(request, user)
                return redirect('main:main')
            else:
                context['error'] = "아이디와 비밀번호를 다시 확인해주세요."

        else:
            context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'
    
    return render(request, 'accounts/login.html', context)

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        
    return redirect('main:main')

lecture/views.py
from django.http.request import QueryDict
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Lecture
from django.utils import timezone
from django.contrib.auth.decorators import login_required
import requests
# Create your views here.

def index(request):

    lectures = Lecture.objects.all().order_by('-created_at')

    context ={
        'lectures' : lectures,
    }

    return render(request, 'lecture/index.html', context)

def detail(request, lecture_id):

    lecture = Lecture.objects.get(id=lecture_id)
    context = {'lecture' : lecture}

    return render(request, 'lecture/detail.html', context)

@login_required
def new(request):

    return render(request, 'lecture/new.html')

@login_required
def create(request):

    user = request.user
    title = request.POST.get('title')
    body = request.POST.get('body')
    image = request.FILES.get('image')
    video_key = request.POST['video_key']

    lecture = Lecture(title=title, user=user, body=body, image=image, created_at=timezone.now(), video_key=video_key)
    lecture.save()

    return redirect('lecture:detail', lecture_id=lecture.id)

@login_required
def edit(request, lecture_id):
   
    try:
        lecture = Lecture.objects.get(id=lecture_id, user=request.user)
    except Lecture.DoesNotExist:
        return redirect('lecture:index')

    context = {'lecture' : lecture}

    return render(request, 'lecture/edit.html', context)

@login_required
def update(request, lecture_id):
    
    try:
        lecture = Lecture.objects.get(id=lecture_id, user=request.user)
    except Lecture.DoesNotExist:
        return redirect('lecture:index')

    lecture.title = request.POST.get('title')
    lecture.body = request.POST.get('body')
    image = request.FILES.get('image')
    
    if image: # image가 none이 아닌경우
        lecture.image = image

    lecture.save()

    context = {'lecture' : lecture}

    return redirect('lecture:detail', lecture_id=lecture.id)  

@login_required     
def delete(request, lecture_id):

    try:
        lecture = Lecture.objects.get(id=lecture_id, user=request.user)
    except Lecture.DoesNotExist:
        return redirect('lecture:index')

    lecture.delete()
    
    return redirect('lecture:index')

@login_required
def like(request, lecture_id):
    try:
        lecture = Lecture.objects.get(id=lecture_id)

        if request.user in lecture.liked_lectures.all():
            lecture.liked_lectures.remove(request.user)
        else:
            lecture.liked_lectures.add(request.user)
            
        return redirect('lecture:detail', lecture_id=lecture.id)
    
    except Lecture.DoesNotExist:
        pass 
    
    return redirect('lecture:index')

main/views.py
from lecture.models import Lecture
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def main(request):
       
   lectures = Lecture.objects.all().order_by('-created_at')[:4]

   context = {'lectures' : lectures}
   return render(request, 'main/main.html', context) 

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/accounts.css' %}">
{% endblock %}

{% block content %}
  
  <div class="container">
      {% if error %}
        <div class="alert alert-danger mt-3">
            {{ error }}
        </div>
      {% endif %}

      <h1>로그인</h1>

      <form method="post" action="{% url 'accounts:login' %}">
          {% csrf_token %}

          <div class="mb-3 col-md-6">
              <label class="form-label" for="username">아이디</label>
              <input class="form-control" id="username" type="text" name="username" placeholder="아이디">
          </div>

          <div class="mb-3 col-md-6">
              <label class="form-label" for="password">비밀번호</label>
              <input class="form-control" id="password" type="password" name="password" placeholder="비밀번호">
          </div>

          <div class="mb-3">
              <button type="submit" class="btn btn-primary">로그인</button>
          </div>
      </form>
  </div>

    
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/accounts.css' %}">
{% endblock %}

{% block content %}  
  <div class="container">
      {% if error %}
        <div class="alert alert-danger mt-3">
            {{ error }}
        </div>
      {% endif %}

      <h2>회원 가입</h2>

      <form method="post" action="{% url 'accounts:sign_up' %}">
          {% csrf_token %}

          <div class="mb-3 col-md-6">
              <label class="form-label" for="username">아이디</label>
              <input class="form-control" id="username" type="text" name="username" placeholder="아이디">
          </div>

          <div class="mb-3 col-md-6">
              <label class="form-label" for="password">비밀번호</label>
              <input class="form-control" id="password" type="password" name="password" placeholder="비밀번호">
          </div>

          <div class="mb-3 col-md-6">
              <label class="form-label" for="password_check">비밀번호 확인</label>
              <input class="form-control" id="password_check" type="password" name="password_check" placeholder="비밀번호 확인">
              <span> </span>
              <span class="help-block" id="validation" style="font-size: 17px;"></span>
           </div>
          
          <div class="mb-3">
              <button type="submit" class="btn btn-primary">회원가입</button>
          </div>
      </form>
  </div>
  <script>
      $("#password_check").on("propertychange change keyup paste input", function() {
        
            const password = $('#password').val();
            const password_check = $('#password_check').val();
        
            console.log('password', password);
            console.log('check', password_check);

            if(password != "" && password_check != "" && typeof password != "undefined" && typeof password_check != "undefined") {
                if(password != password_check) {
                    var goal = $("#validation");
                        goal.text("비밀번호가 일치하지 않습니다.");
                                            
                        $("#validation").css("color", "red");
                } else if (password_check == password_check) {
                    var goal = $("#validation");
                        goal.text("비밀번호가 일치합니다.");
                        $("#validation").css("color", "green");
                }
            }
        });
  
    
    </script>
    
{% endblock %}

lecture/templates/lecture/detail.html
    {% extends 'base.html' %} <!-- 항상 맨위에 위치해야 된다-->

    {% load static %}

    {% block style %}
        <link rel="stylesheet" href="{% static 'lectures/style.css' %}">
    {% endblock %}
 
    {% block content %}

    <div class="container">
    <h1>Lecture Detail</h1>
    
    <table class="table table-sm table-Info">
        <thead>
          <tr>
            <th scope="col"><input readonly id="title" type="text" name="title" class="form-control-plaintext" value="{{ lecture.title }}"></th>
            <th scope="col">등록자</th>            
          </tr>
        </thead>
        <tbody>
          <tr>
            <td table-active"><div id="player"></div></td>
            <td><input readonly id="Author" type="text" name="author" class="form-control-plaintext" value="{{ lecture.user.get_username }}"></td>
            </tr>
            <tr>
                <td>등록일</td>
                <td>{{ lecture.created_at }}</td>
            </tr>           
            <tr>
                <td>좋아요</td>
                <td>{{ lecture.liked_lectures.count }}</td>
            </tr>
            
        </tbody>
      </table>
    
      {% if user.is_authenticated %}
      <form action="{% url 'lecture:like' lecture.id %}" method="post">
          {% csrf_token %}
          
          <!-- 현재 유저가 좋아요를 누른 사용자들 안에 있다면 -->
          {% if user in lecture.liked_lectures.all %}
            <button type="submit" class="btn btn-secondary">
                 LIKE
              </button>
             {% else %}
              
                <button type="submit" class="btn btn-primary">
                  LIKE
              </button>
          {% endif %}
      </form>
      {% endif %}
    
    <div class="mb-3 col-md-6">
        <label for="body" class="form-label">강의 소개</label>
        <textarea readonly id="body" name="body" class="form-control-plaintext">{{ lecture.body }}</textarea>
    </div>    

    <!-- <a href="/posts">목록</a> -->
    <button type="submit" class="btn btn-success"> <a href="{% url 'lecture:index' %}">목록</a></button>

    <!-- 본인이 작성한 게시물만 수정하기 삭제하기 버튼이 보인다. -->
    {% if user == lecture.user %}
    <button type="submit" class="btn btn-info"> <a href="{% url 'lecture:edit' lecture.id %}">수정하기</a></button>

    <button type="submit" class="btn btn-danger" onclick="deletess()"> <a href="{% url 'lecture:delete' lecture.id %}">삭제하기</a> </button>
    {% endif %}
    </div>

    <script>
       var tag = document.createElement('script');

        tag.src = "https://www.youtube.com/iframe_api";
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

        var player;
        function onYouTubeIframeAPIReady() {
            player = new YT.Player('player', {
                videoId: '{{ lecture.video_key }}'
            });
        }

        function deletess() {
          if (window.confirm("정말 삭제 하시겠습니까?")) {
            
          } else {
            return;
          }

        }
    </script>

    {% endblock %}

lecture/templates/lecture/edit.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
        <link rel="stylesheet" href="{% static 'lectures/style.css' %}">
    {% endblock %}   
{% block content %}

  
 

<div class="container">
<h1>Edit Post</h1>

        <!-- {% if lecture.image %}
            <div class="mb-3 col-md-6">
                <img src="{{ lecture.image.url }}" alt="Post Image" class="img-fluid">
            </div>
        {% endif%} -->
    

<!-- create/ 마지막에 /를 붙여야한다 -->
<!-- <form method = "POST" action="/posts/create/"> -->
<form method = "POST" action="{% url 'lecture:update' lecture.id %}" enctype="multipart/form-data">    

<!-- csrf 위조공격 -->
<!-- request에 csrf토큰을 같이 보내서 우리가 보낸건지 해커가 보낸건지 구분한다 -->
{% csrf_token %}
<!-- <div class="mb-3 col-md-6">
    <label for="Author" >Author</label>
    <input id="Author" type="text" name="author" value="{{post.author}}">
</div> -->
<div class="mb-3 col-md-6">
    <label for="title" class="form-label">제목</label>
    <textarea id="title" cols="1" rows="1" name="title" class="form-control">{{lecture.title}}</textarea>
</div>   

<div class="mb-3 col-md-6">
    <label for="body" class="form-label">본문</label>
    <textarea id="body" cols="30" rows="10" name="body" class="form-control">{{lecture.body}}</textarea>
</div>    

<div class="mb-3 col-md-6">
    <label for="image" class="form-label">이미지</label>
    <input type="file" class="form-control" id="image" name="image">
</div>

<div class="mb-3">
    <button type="submit" class="btn btn-primary">수정하기</button>
</div>
</form>


<button class="btn btn-primary "><a href="{% url 'lecture:index' %}">목록</a></button>
</div>
{% endblock %}

lecture/templates/lecture/index.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'lectures/style.css' %}">
{% endblock %}
{% block content %}

    <!-- header -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="/main/" style="margin: 5px; color: green;" > 멋프런</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample03">
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item" style="margin-left: 35px;">
              <a class="text-decoration-none" href="{% url 'lecture:index' %}">
                <!-- <button class="btn btn-light">모든 강의</button>  -->
                <div style="font-size: 19px; color: white; margin-top: 6px;">모든 강의</div>
              </a>
              <!-- <a class="text-decoration-none" href="{% url 'lecture:index' %}">모든 강의</a> -->
              <!-- <a class="nav-link" href="#">모든 강의</a> -->
            </li>
      
            <!-- 로그인이 되어 있는 경우 -->
            {% if user.is_authenticated %}
            <form method="POST" action="{% url 'accounts:logout' %}">
              {% csrf_token %}
              
              <!-- 장고 userModel 함수 -->
              <span style="font-size: 18px; color: white; margin-left: 25px;">{{ user.get_username }}님 환영합니다.</span> 
              <button type="submit" class="btn btn-primary ms-3 pull-right">LOGOUT</button>
            {% else %}
            </div>
             <li class="nav-item justify-content-end ">
              <a class="text-decoration-none" href="{% url 'accounts:login' %}">
                 <button class="btn btn-primary ">로그인</button>
               </a>
            </li>
      
            <li class="nav-item justify-content-end">
              <a class="text-decoration-none" href="{% url 'accounts:sign_up' %}">
                <button class="btn btn-primary ms-3 " style="margin-right: 20px;">회원가입</button>
            </a>
            </li>
            {% endif %}
      
          </ul>
          <!--  -->
      
          
        </div>
      </nav>
    <!-- header end -->
    &nbsp; 
      


    <div class="container">
        <h1>모든 강의</h1>
        <button type="button" class="btn btn-outline-success"><a href="/lecture/new/">동영상 등록하기</a></button>
        <br>
        <br>
        <br>
    {% if lectures %}

      {% for lecture in lectures %}
        {% if lecture.image %}
            
        <div class="lecture" >
            <div class="mb-3 col-md-6">
                <a href="{% url 'lecture:detail' lecture.id %}"> <img src="{{ lecture.image.url }}" alt="Post Image" class="content-img"></a>
            </div>
        </div>
        {% endif%}
        {% endfor %}

      
  
<!-- <ul>
    {% for post in posts %}
         <li>Author : {{post.author}} | Body: {{post.body}}</li>
    {% endfor %}
</ul>
-->
{% else %}
    <p>No lecture</p>
{% endif %}



    <!-- {% if dog %}
    <div class="card mt-3">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ dog }}" alt="Dog Image" class="card-img">
            </div>
            <div class="col-md-8 card-body">
                <h5 class="card-title">강아지를 보고 싶다면?</h5>
                <p class="card-text">Dog API를 사용합시다.</p>
                <a href="https://dog.ceo/dog-api/" class="card-link" target="_blank">Dog API</a>
            </div>

        </div>
    </div>

    {% endif %} -->

</div>
{% endblock %}

lecture/templates/lecture/new.html
{% extends 'base.html' %}

{% load static %}

    {% block style %}
        <link rel="stylesheet" href="{% static 'lectures/style.css' %}">
    {% endblock %}
{% block content %}



<div class="container">
    <h1>New lecture</h1>
<!-- create/ 마지막에 /를 붙여야한다 -->
<!-- <form method = "POST" action="/posts/create/"> -->
<form method = "POST" action="{% url 'lecture:create' %}" enctype="multipart/form-data">    
       
<!-- csrf 위조공격 -->
<!-- request에 csrf토큰을 같이 보내서 우리가 보낸건지 해커가 보낸건지 구분한다 -->
{% csrf_token %}
 <!--margin bottom 3-->
<!-- <div class="mb-3 col-md-6">
    <label for="Author"  class="form-label">Author</label>
    <input id="Author" type="text" name="author" class="form-control">
</div> -->

<div class="mb-3 col-md-6">
    <label for="title" class="form-label">제목</label>
    <textarea id="title" cols="1" rows="1" name="title" class="form-control"></textarea>
</div>    

<div class="mb-3 col-md-6">
    <label for="body" class="form-label">본문</label>
    <textarea id="body" cols="30" rows="10" name="body" class="form-control"></textarea>
</div>    

<div class="mb-3 col-md-6">
    <label for="image" class="form-label">이미지</label>
    <input type="file" class="form-control" id="image" name="image">
</div>

<div class="mb-3 col-md-6">
    <label for="video_key">Video Key</label>
    <input type="text" name="video_key" class="form-control" id="video_key" placeholder="Video Key">
</div>

<div class="mb-3">
    <button type="submit" class="btn btn-primary">작성하기</button>
</div>

</form>


<!-- <a href="{% url 'lecture:index' %}">목록</a> -->
</div>

{% endblock %}

main/templates/main/main.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- Header -->
    <!-- 상단 메뉴바{s} -->

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="/main/" style="margin: 5px; color: green;" > 멋프런</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExample03">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item" style="margin-left: 35px;">
        <a class="text-decoration-none" href="{% url 'lecture:index' %}">
           <div style="font-size: 19px; color: white; margin-top: 6px;">모든 강의</div>
        </a>       
      </li>

      <!-- 로그인이 되어 있는 경우 -->
      {% if user.is_authenticated %}
      <form method="POST" action="{% url 'accounts:logout' %}">
        {% csrf_token %}
        
        <span style="font-size: 18px; color: white; margin-left: 25px;">{{ user.get_username }}님 환영합니다.</span> 
        <button type="submit" class="btn btn-primary ms-3 pull-right">LOGOUT</button>
      {% else %}
      </div>
       <li class="nav-item justify-content-end ">
        <a class="text-decoration-none" href="{% url 'accounts:login' %}">
           <button class="btn btn-primary ">로그인</button>
         </a>
      </li>

      <li class="nav-item justify-content-end">
        <a class="text-decoration-none" href="{% url 'accounts:sign_up' %}">
          <button class="btn btn-primary ms-3 " style="margin-right: 20px;">회원가입</button>
      </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

    <!-- Swiper -->
  <div class="swiper-container">
    <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="{% static '/images/001.png' %}" alt="lion01">
      </div>
      <div class="swiper-slide"><img src="{% static '/images/002.png' %}" alt="lion01">
      </div>
      <div class="swiper-slide"><img src="{% static '/images/querydsl.png' %}" alt="lion01">
      </div> 
      <div class="swiper-slide"><img src="{% static '/images/네카라쿠배.png' %}" alt="lion01">
      </div>       
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>

  <!-- content영역 -->
  <div class="container2">
  <div class="content_container">
    {% for lecture in lectures %}
        {% if lecture.image %}
         <div class="content-img">
                <img src="{{ lecture.image.url }}" alt="Post Image" class="img-fluid" style="width: 100%; height: 100%;">
            </div>
        {% endif%}
    {% endfor %}
   
  </div>

  </div>

    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
        var swiper = new Swiper('.swiper-container', {
      spaceBetween: 30,
      centeredSlides: true,
      autoplay: {
        delay: 2500,
        disableOnInteraction: false,
      },
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
    </script>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block style %}
    {% endblock %}
    <title>Main</title>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<body>
    
    {% block content %}
    {% endblock %}
<script>

</script>
</body>
</html>